### ISSUE TITLE
Hero section

### ISSUE THREAD

**Issue by judewoolls** [judewoolls/p1-test-brief#1]
“As a user, I want to feel welcomed and supported, so I am encouraged to reach out for help if needed.”

**Acceptance criteria**

- [ ] Display a suitable hero image
- [ ] Have a clear title and subtitle
- [ ] A call to action button is displayed clearly

**Tasks**

- [ ] Add a hero background image.
- [ ] Add a subtitle and call to action button
