### ISSUE TITLE
Additional Section - Support Services:

### ISSUE THREAD

**Issue by judewoolls** [judewoolls/p1-test-brief#2]
As a person who is looking for help I want to be able to learn about the different types of help so that i can compare and access the one i want

**Tasks**

- [ ] Create a support page
- [ ] Create a description of different types of support
- [ ] In each section there should be cards for each support service.
- [ ] Each card should have a button that links to the site
